### PR TITLE
Allow self signed certificates

### LINKED ISSUE #100: Add an option to support self-signed or non-valid https server certificates
At this moment if the XXsonic server are using a non-valid/self-signed https certificate, Ultrasonic cannot connect with them giving a _network error_.

Will be interesting add an option (disabled by default) to ignore server certificate and connect anyway.

This bug may be related with #99

### PR DESCRIPTION
**Pull request by Tapchicoma**
Fixes #100 and #99.

Translations was done in Google translate - may be not correct.

### CODE REVIEW

**Comment by Tapchicoma** [comment]
Should be released as 2.0.1 version, that is reason for merging in master.

After merge I will merge master into develop.

**Review by ogarcia — CHANGES_REQUESTED** [review]
The change is not working for me in my test setup.

I have a ssl certificate with a CN `myserver.example.com`, but I'm connecting to my server via `subsonic.example.com`.

This is the log:
```
12-25 22:06:00.713 7351-10326/org.moire.ultrasonic D/OkHttp: --> GET https://subsonic.example.com:8080/rest/ping.view?u=ogarcia&c=UltraSonic%2520for%2520Android&f=json&v=1.7.0&p=enc:63687570617264656C63616E75746F
12-25 22:06:00.713 7351-10326/org.moire.ultrasonic D/OkHttp: --> END GET
12-25 22:06:00.916 7351-10326/org.moire.ultrasonic D/OkHttp: <-- HTTP FAILED: javax.net.ssl.SSLPeerUnverifiedException: Hostname subsonic.example.com not verified:
12-25 22:06:00.918 7351-10326/org.moire.ultrasonic D/OkHttp:     certificate: sha256/bFRniO4s6eNHQZAyaFrh9Mmo3xS5oBS8j3DVtiKqd3M=
12-25 22:06:00.918 7351-10326/org.moire.ultrasonic D/OkHttp:     DN: CN=myserver.example.com
12-25 22:06:00.918 7351-10326/org.moire.ultrasonic D/OkHttp:     subjectAltNames: [myserver.example.com]
12-25 22:06:00.919 7351-10326/org.moire.ultrasonic D/MusicServiceFactory: Resetting music service
12-25 22:06:00.979 7351-7351/org.moire.ultrasonic W/ServerSettingsFragment: javax.net.ssl.SSLPeerUnverifiedException: Hostname subsonic.example.com not verified:
                                                                                certificate: sha256/bFRniO4s6eNHQZAyaFrh9Mmo3xS5oBS8j3DVtiKqd3M=
                                                                                DN: CN=myserver.example.com
                                                                                subjectAltNames: [myserver.example.com]
                                                                            javax.net.ssl.SSLPeerUnverifiedException: Hostname subsonic.example.com not verified:
                                                                                certificate: sha256/bFRniO4s6eNHQZAyaFrh9Mmo3xS5oBS8j3DVtiKqd3M=
                                                                                DN: CN=myserver.example.com
                                                                                subjectAltNames: [myserver.example.com]
                                                                                at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:308)
                                                                                at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
                                                                                at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
                                                                                at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
                                                                                at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
                                                                                at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
                                                                                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at org.moire.ultrasonic.api.subsonic.interceptors.RangeHeaderInterceptor.intercept(RangeHeaderInterceptor.kt:31)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at org.moire.ultrasonic.api.subsonic.interceptors.PasswordHexInterceptor.intercept(PasswordHexInterceptor.kt:23)
                                                                                at org.moire.ultrasonic.api.subsonic.interceptors.ProxyPasswordInterceptor.intercept(ProxyPasswordInterceptor.kt:19)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at org.moire.ultrasonic.api.subsonic.interceptors.VersionInterceptor.intercept(VersionInterceptor.kt:38)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at org.moire.ultrasonic.api.subsonic.SubsonicAPIClient$okHttpClient$2.intercept(SubsonicAPIClient.kt:73)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                                at okhttp3.RealCall.execute(RealCall.java:77)
                                                                                at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                                at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                                                at org.moire.ultrasonic.service.RESTMusicService.ping(RESTMusicService.java:130)
                                                                                at org.moire.ultrasonic.service.CachedMusicService.ping(CachedMusicService.java:89)
                                                                                at org.moire.ultrasonic.fragment.ServerSettingsFragment$1.doInBackground(ServerSettingsFragment.java:234)
12-25 22:06:00.979 7351-7351/org.moire.ultrasonic W/ServerSettingsFragment:     at org.moire.ultrasonic.fragment.ServerSettingsFragment$1.doInBackground(ServerSettingsFragment.java:222)
                                                                                at org.moire.ultrasonic.util.ModalBackgroundTask$3.run(ModalBackgroundTask.java:93)
```

**Comment by Tapchicoma** [comment]
This behaviour was by intention: the CN name in certifcate and actual domain name should be the same. At least is sets some level of security. Or you think it should allow certificate for any domain name?

**Comment by ogarcia** [comment]
I think that when anyone enable the _Allow self-signed HTTPS certificate_ option expects that all certificate verification was disabled. He/She only wants the SSL encryption.

Moreover, almost everyone who generates self-signed certificates does with a tool that brings the OpenSSL package that gives to the certificate a name that not matches with the URL that they are using.

IMHO, the option must disable all certificate checks and use any not expired certificate.

In the other hand (I don't know what difficult to implement is this), I think that be a good idea give a different error in case of have a certificate problem. But only if is trivial to make it, if not, the generic error is ok.

**Comment by Tapchicoma** [comment]
Updated PR - now it should allow any CN in certificate.

**Pull request merged**
