### PR TITLE
Refactor menudrawer to navigationui

### LINKED ISSUE #310: Drop menudrawer an use NavigationUI
## Problem description

Current menudrawer is legacy code that can cause problems in future. It must be replaced with [NavigationUI](https://developer.android.com/guide/navigation/navigation-ui)

### PR DESCRIPTION
**Pull request by nitehu**
Resolves #310 
The menundrawer library is now removed from Ultrasonic, all its functionality is replaced with Android NavigationUI.
Other related changes:
- All Activities are now Fragments, there is a single activity remained which loads and switches between them
- The bloated SubsonicTabActivity base class is removed, its functionality is split into smaller classes, injected by DI
- We already started to use the SwipeRefresh's progress indicator instead of the old progress bar, now the old one is fully replaced
- The mini NowPlaying is also a Fragment now living its own life at the bottom
- Other small changes which needed because SubsonicTabActivity is gone

This is a large refactor so I'll test it for a while to see if everything works as intended and will try to find remaining bugs.
Also there may be unused fragments or other strangeness left in the code so I'll try to clean it up more.

Any feedback is welcomed.

### CODE REVIEW

**Comment by Maxmystere** [comment]
```
Android API level: 30
Ultrasonic version name: 2.18.0
Ultrasonic version code: 88


java.lang.RuntimeException: Unable to start activity ComponentInfo{org.moire.ultrasonic.debug/org.moire.ultrasonic.activity.NavigationActivity}: java.lang.ClassCastException: org.moire.ultrasonic.util.TimeSpanPreference cannot be cast to android.preference.Preference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8007)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassCastException: org.moire.ultrasonic.util.TimeSpanPreference cannot be cast to android.preference.Preference
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:49)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:497)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:502)
	at android.preference.GenericInflater.inflate(GenericInflater.java:334)
	at android.preference.GenericInflater.inflate(GenericInflater.java:271)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:343)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:670)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:629)
	at org.moire.ultrasonic.activity.NavigationActivity.loadSettings(NavigationActivity.kt:289)
	at org.moire.ultrasonic.activity.NavigationActivity.onCreate(NavigationActivity.kt:149)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3602)
	... 11 more

```

**Comment by ogarcia** [comment]
@nitehu is a great, impresive work and I love it! :clap: :clap: :clap: 

Now we need to do intensive tests to find bugs, as you said, is a HUGE change.

**Comment by ogarcia** [comment]
The @Maxmystere error can be reproduced using emulator with API level 21 (Android 5.0)

**Comment by nitehu** [comment]
Yes, thank you guys, I think this was a first startup problem. Also I guess there may be another bug as I didn't see the Welcome dialog while starting on the new emulator. Will check that too.
Edit: Ok the welcome screen works fine, just that the first start of the new emulator was the crash, so when I finally managed to start it really that wasn't the first time for Ultrasonic 😂

**Comment by Moto-John** [comment]
Could we maybe get a debug apk? We can then help with bugs (plus I really want to checkout the new version)

**Comment by Maxmystere** [comment]
Here is current branch that I built from my codespace (I just hate command line android build)

App is launching now but I can't add a server
If you add a server from an older version then update it everything is running perfectly

(This is not a zip ! Just remove .not.zip on filename)
[ultrasonic-debug.apk.not.zip](https://github.com/ultrasonic/ultrasonic/files/5992434/ultrasonic-debug.apk.not.zip)

**Comment by Moto-John** [comment]
Thanks Maxmystere. I can unfortunately confirm that adding a server doesn't work

**Comment by nitehu** [comment]
Thank you guys, as I found out the server saving was a miracle for working at all until now. It is fixed now I hope.
Also, @Moto-John please find a new debug apk [here](https://github.com/nitehu/ultrasonic/releases/tag/2.18.1-beta.1).

**Comment by nitehu** [comment]
Ok, I've checked everything I could think of. Please let me know if you guys find any bugs.
Please find a fresh debug APK [here ](https://github.com/nitehu/ultrasonic/releases/tag/2.18.1-beta.2)if you need one.

**Comment by ogarcia** [comment]
Ok. I will test it along this week :wink:

**Comment by jerome-pouiller** [comment]
I have just tested and it is great!

**Review by ogarcia — APPROVED** [review]
LGTM. @nitehu I don't found issues. If you are happy too, please merge in develop to I can build a new release.

**Comment by ogarcia** [comment]
Published!

**Pull request merged**
