### PR TITLE
Convert LRUCache to Kotlin

### PR DESCRIPTION
**Pull request by tzugen**
as above.

### CODE REVIEW

**Comment by ogarcia** [comment]
@tzugen do you think that this PR is ready to test (and merge) or do you want make changes?

**Comment by nitehu** [comment]
I think it's assigned to me because it should be reviewed.
I hadn't start it because I was waiting for the previous version with the database versioning fixes to roll out.

**Comment by ogarcia** [comment]
@tzugen Ok, perfect. I'll release now the 3.0.1 with #671 and latest translations and (if google wants) I think that we can revert to database update to 3.1.0 :wink:

**Review by nitehu — APPROVED** [review]
Review OK

**Pull request merged**
