### PR TITLE
More tiny and pretty ic_empty icon

### PR DESCRIPTION
**Pull request by ogarcia**

### CODE REVIEW

**Comment by ogarcia** [comment]
Is a stupid change, but I think that looks better

**Comment by tzugen** [comment]
Can you give a screenshot?

**Comment by ogarcia** [comment]
Yezzz!
photo_2021-12-24_19-46-49

**Comment by tzugen** [comment]
The icon is OK, but if we use it in this big size, the line weight should be thinner in my opinion...

**Comment by ogarcia** [comment]
> The icon is OK, but if we use it in this big size, the line weight should be thinner in my opinion...

Ok. For now we leave this and I take note to make it more thin in future.

**Pull request merged**
