### PR TITLE
Larger image cache

### LINKED ISSUE #531: New image loader must be improved
The new image uploader always re-downloads the images in all lists, these must be stored on the device and should only be reloaded if the user requests a list refresh. This is worse in artist's list where images are reloaded again and again in a simple scroll.

In the other hand, the album covers have the red/green triange in upper left corner (I think that we can remove it).

IMHO, if we want to do a new release must fix this issue or revert #514

### PR DESCRIPTION
**Pull request by tzugen**
Fixes #531 

Increases the memory cache to 25% of the available ram of the app (was 14% before)

### CODE REVIEW

**Comment by tzugen** [comment]
(also fixes a leak in UpdateView)

**Comment by ogarcia** [comment]
Seems to have a crash: [ultrasonic-stacktrace.txt](https://github.com/ultrasonic/ultrasonic/files/6707092/ultrasonic-stacktrace.txt)
:cry: 

Simply open app, and go to artist list

**Comment by tzugen** [comment]
I cant reproduce on device or emulator... Maybe clean the project?
Or you can set some breakpoints to find out  what failed?

**Comment by ogarcia** [comment]
The problem must be related to server version, because with sample server works well (but with Supysonic doesn't)

**Comment by tzugen** [comment]
Feel free to send me server credentials per mail to check it out.

**Comment by ogarcia** [comment]
> Feel free to send me server credentials per mail to check it out.

Yezz. I'm deploying a server to make tests :wink: (give me some time to do this, too much work today)

**Comment by ogarcia** [comment]
@tzugen I sent you the credentials via gitter :wink:

**Comment by ogarcia** [comment]
Steps to reproduce:
1. Open clean install of Ultrasonic
2. On welcome screen press OK to add demo server
3. Go to servers and add my server (don't delete demo server)
4. Exit app
5. Enter app and open demo server, go artist list
6. Switch to my server and go artist list
7. If don't crash switch between demo and my server and go artist list (sometimes the first time you enter works well)
8. Once first crash, crash always

**Comment by tzugen** [comment]
I have to say I don't really like koin.
It comes with the promises to make things magically easier,
but for now the magic mostly made more problems than before.

It hides the real error.
The real error is this:
```
java.lang.IllegalArgumentException: Unknown api version V1_10_2
	org.moire.ultrasonic.api.subsonic.SubsonicAPIVersions$Companion.getClosestKnownClientApiVersion(SubsonicAPIVersions.kt:39)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$4.invoke(MusicServiceModule.kt:58)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$4.invoke(MusicServiceModule.kt:51)
	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:48)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:46)
	org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:46)
	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
	org.koin.core.scope.Scope.resolveInstance(Scope.kt:218)
	org.koin.core.scope.Scope.get(Scope.kt:204)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$6.invoke(MusicServiceModule.kt:96)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$6.invoke(MusicServiceModule.kt:71)
	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:48)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:46)
	org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:46)
	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
	org.koin.core.scope.Scope.resolveInstance(Scope.kt:218)
	org.koin.core.scope.Scope.get(Scope.kt:204)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$9.invoke(MusicServiceModule.kt:96)
	org.moire.ultrasonic.di.MusicServiceModule$musicServiceModule$1$9.invoke(MusicServiceModule.kt:81)
	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:48)
	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:46)
	org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:46)
	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
	org.koin.core.scope.Scope.resolveInstance(Scope.kt:218)
	org.koin.core.scope.Scope.get(Scope.kt:204)
	org.moire.ultrasonic.subsonic.ImageLoaderProvider.getImageLoader(ImageLoaderProvider.kt:84)
	org.moire.ultrasonic.fragment.NowPlayingFragment.update(NowPlayingFragment.java:111)
	org.moire.ultrasonic.fragment.NowPlayingFragment.onResume(NowPlayingFragment.java:86)
	androidx.fragment.app.Fragment.performResume(Fragment.java:3026)
	androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:604)
	androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
	androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
	androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
	androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3070)
	androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
	androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
	androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
	androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:204)
	android.app.Activity.performResume(Activity.java:7983)
	android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	android.os.Handler.dispatchMessage(Handler.java:107)
	android.os.Looper.loop(Looper.java:214)
	android.app.ActivityThread.main(ActivityThread.java:7356)
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by tzugen** [comment]
It is unrelated to this PR, but its good that you found this

**Comment by tzugen** [comment]
It was a mistake I made in d9a7fa2
Which was part of https://github.com/ultrasonic/ultrasonic/pull/517

**Review by ogarcia — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
