### PR TITLE
TrackCollectionFragment: fix play all button

### PR DESCRIPTION
**Pull request by blastrock**
This is a bugfix. Whenever I press the play all button on a folder with no tracks, it would load an empty playlist instead of recursively adding all the subfolders.

It looks like the folders aren't `MusicDirectory.Entry` but `MusicDirectory.Album`.

Note: I am using airsonic as my backend.

### CODE REVIEW

**Comment by nitehu** [comment]
Thank you for your contribution!
As the [contribution guide](https://github.com/ultrasonic/ultrasonic/blob/develop/CONTRIBUTING.md) writes, you should sign your commits for us to be able to merge them.
You should [set up a signing key in github](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) to do this, or if you prefer, I can re-create this PR and sign it with my key (but then unfortunately my name will appear beside it...)
Please let us know how should we proceed.

**Comment by blastrock** [comment]
I'll set it up, I plan on contributing more to this project :)

I'll fix the CI too

**Comment by blastrock** [comment]
Got it working, CI should be fixed too, thanks :)

**Review by nitehu — APPROVED** [review]
Review OK, tests OK

**Pull request merged**
