### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small and useless PR adds two buttons to get your app on F-Droid and the Play Store.

Thanks for this app :)

### CODE REVIEW

**Comment by ogarcia** [comment]
Is good idea add the badges, but please close this PR and send a new one into develop branch.

**Comment by Poussinou** [comment]
Hi @ogarcia 
I changed the branch for this PR as you can see.

Thanks for your quick answer !

**Comment by ogarcia** [comment]
@Poussinou The [README.md](https://github.com/ultrasonic/ultrasonic/blob/develop/README.md) in develop branch was rewritten for the new 2.0.0 version. We cannot merge this PR because you are using an old version of file. 😞 

Please close this PR and send the changes in a new one using the file of develop branch.

**Comment by Poussinou** [comment]
Oops OK !

**Pull request closed without merging**
