### PR TITLE
Add migration path for coming DB change

### PR DESCRIPTION
**Pull request by tzugen**
See #718 . This is step 1.

### CODE REVIEW

**Comment by tzugen** [comment]
I split the rename into a seperate PR for easier review => #722

**Comment by ogarcia** [comment]
I'm not sure if the issue is caused by this PR or #722, but Ultrasonic cannot be launched:
```
E/UncaughtExceptionHandler: Uncaught Exception! Android API level: 28
    Ultrasonic version name: 3.1.1
    Ultrasonic version code: 102
    
    
    java.lang.ClassCastException: org.moire.ultrasonic.domain.MusicDirectory$Entry cannot be cast to org.moire.ultrasonic.domain.Track
        at org.moire.ultrasonic.service.Downloader.addToPlaylist(Downloader.kt:372)
        at org.moire.ultrasonic.service.MediaPlayerController.addToPlaylist(MediaPlayerController.kt:177)
        at org.moire.ultrasonic.service.MediaPlayerController.restore(MediaPlayerController.kt:74)
        at org.moire.ultrasonic.service.MediaPlayerLifecycleSupport$onCreate$2.invoke(MediaPlayerLifecycleSupport.kt:63)
        at org.moire.ultrasonic.service.MediaPlayerLifecycleSupport$onCreate$2.invoke(MediaPlayerLifecycleSupport.kt:61)
        at org.moire.ultrasonic.service.PlaybackStateSerializer.deserializeNow(PlaybackStateSerializer.kt:104)
        at org.moire.ultrasonic.service.PlaybackStateSerializer.access$deserializeNow(PlaybackStateSerializer.kt:29)
        at org.moire.ultrasonic.service.PlaybackStateSerializer$deserialize$1.invokeSuspend(PlaybackStateSerializer.kt:84)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

To reproduce it:
1. Uninstall Ultrasonic.
2. Install from master (stable version).
3. Upgrade to this branch.
4. Crash (boom bang)

**Comment by tzugen** [comment]
Yes! I couldn't reproduce it on the device, but it makes sense. 
There was a try block without catch.

**Review by ogarcia — APPROVED** [review]
LGTM

**Pull request merged**
