### PR TITLE
New 2.0.0 release

### PR DESCRIPTION
**Pull request by Tapchicoma**
Finally after almost half a year there is something to release.

Please test it and feel free to open bug issues.

### CODE REVIEW

**Comment by ogarcia** [comment]
Great job!

Today I'm AFK (only mobile connection). But tomorrow I will make several tests and merge it (or open bugs if not work).

**Comment by craftyguy** [comment]
This is exciting! I could help test if you can provide a 'beta' release or something. I'm not set up to build android apps :(

**Comment by Tapchicoma** [comment]
@ogarcia I've updated this PR, now it should work with supysonic.

**Comment by ogarcia** [comment]
@Tapchicoma Tested! (Sorry for delay, I'm out-of-world this weekend) For me works like a charm!

We need to update version code and version name. I can do the work, merge into master and tag it.

**Comment by ogarcia** [comment]
Ah, we need some fancy text to put in Play Store as update info. :smile:

**Review by ogarcia — APPROVED** [review]

**Pull request merged**
