### PR TITLE
Refactor and redesign artist list

### LINKED ISSUE #304: Improve artists list with an alphabetic side index
A good improvement will be an alphabetic side index in artist list [like in this example][1] or like the contacts app:
image

For me, more beautiful is the contacts app.

[1]: https://medium.com/@mail.shaktisinh/alphabetic-side-index-in-android-ed3c4e3cda67

### PR DESCRIPTION
**Pull request by nitehu**
Closes #304 
This PR contains the following changes:
- Updated the SelectArtistActivity to Kotlin, changed it to use RecyclerView
- Changed the old progress display to use the SwipeRefreshLayout's spinner
- Added alphabetic side index, enabled RecyclerView's built-in FastScroll
- Added displaying "coverArt" images for Artists

I also had a fair amount of problems trying to make the Artis list as modern and nice as possible.
- The current FastScroll has many problems, e.g. the thumb can be too small for long Artist lists. I've tried to add an external FastScroll library, but the ones I've found require a minimum API level of at least 16... Any suggestions are welcome
- As I've found out, the Artist list has two distinct modes, depending on wether the "ID3 Tags" are enabled in the settings or not. If they are enabled, Ultrasonic will use the getArtists API which returns the coverArt IDs for the artists. However, if the ID3 is disabled, Ultrasonic uses the getIndexes API, which won't return the coverArt.
  I'm not sure if this is OK, or the ImageLoader should be able to issue that missing getArtist request to get all of the details of an Artist. Also, currently I've just reused the unknown album image for artists, maybe they should have a separate icon? 
- I've added some rounded corners to the icons, but they can be fully circular if that's better
- I think a "search/filter" box also can be added to this list, but maybe that is really deserves its own separate issue.

Currently it looks like this:
Screenshot 2020-11-18 213245

@ogarcia What do you think? What improvements should I make?

### CODE REVIEW

**Comment by ogarcia** [comment]
Very good PR!!! Today I have much work, but tomorrow afternoon I'll do a try and tell you my feedback :wink:

**Comment by ogarcia** [comment]
> * The current FastScroll has many problems, e.g. the thumb can be too small for long Artist lists. I've tried to add an external FastScroll library, but the ones I've found require a minimum API level of at least 16... Any suggestions are welcome

Maybe is time to set `minSdk: 16`. I think that we can drop support to Android 4.0, since the vast majority of 4.0 devices were updated to 4.4 an Google Play Services support for 4.0 ended in February 2019.

I like this (the first bubble in left screenshot): https://github.com/zhanghai/AndroidFastScroll but I don't check the minimum API level that have.

> * As I've found out, the Artist list has two distinct modes, depending on wether the "ID3 Tags" are enabled in the settings or not. If they are enabled, Ultrasonic will use the getArtists API which returns the coverArt IDs for the artists. However, if the ID3 is disabled, Ultrasonic uses the getIndexes API, which won't return the coverArt.

This is true since getIndexes always run (even if you don't have ID3 Tags because use the folder names in the server) and getArtists only if you have your tags well. I think that we can add a new setting like __Show artist picture in artist list__ under __ID3 Tags__ option. If you have __ID3 Tags__ disabled cannot enable __Show artist picture__. And if you have __ID3 Tags__ enabled you have the option to show pictures or not. This is because some servers like __Supysonic__ don't support artist picture and if you are going to have the full list with default image is better have more space to artist name.

Talking about space. I think that can reduce margins between index letter and artist picture because is bery big in small screens. See the difference.

Before:
Screenshot_20201120-093116_Ultrasonic

After:
Screenshot_20201120-092327_Ultrasonic

The diff:
```diff
  diff --git a/ultrasonic/src/main/res/layout/artist_list_item.xml b/ultrasonic/src/main/res/layout/artist_list_item.xml
  index fd7009f9..dc1efa3f 100644
  --- a/ultrasonic/src/main/res/layout/artist_list_item.xml
  +++ b/ultrasonic/src/main/res/layout/artist_list_item.xml
  @@ -13,12 +13,12 @@
           a:layout_width="wrap_content"
           a:layout_height="wrap_content"
           a:gravity="center_horizontal|center_vertical"
  -        a:minWidth="72dip"
  +        a:minWidth="56dip"
           a:minHeight="56dip"
  -        a:paddingStart="16dip"
  -        a:paddingLeft="16dip"
  -        a:paddingEnd="16dip"
  -        a:paddingRight="16dip"
  +        a:paddingStart="8dip"
  +        a:paddingLeft="8dip"
  +        a:paddingEnd="8dip"
  +        a:paddingRight="8dip"
           a:text="A"
           a:textAppearance="?android:attr/textAppearanceLarge"
           a:textColor="@color/cyan" />
  @@ -33,10 +33,10 @@
           a:layout_toRightOf="@+id/row_section"
           a:layout_gravity="center_horizontal|center_vertical"
           a:layout_marginTop="8dp"
  -        a:layout_marginLeft="8dp"
  -        a:layout_marginRight="16dp"
  -        a:layout_marginStart="8dp"
  -        a:layout_marginEnd="16dp" />
  +        a:layout_marginLeft="2dp"
  +        a:layout_marginRight="10dp"
  +        a:layout_marginStart="2dp"
  +        a:layout_marginEnd="10dp" />
   
       <TextView
           a:id="@+id/row_artist_name"
  @@ -49,5 +49,7 @@
           a:minHeight="56dip"
           a:paddingLeft="3dip"
           a:paddingRight="3dip"
  +        a:layout_marginRight="12dp"
  +        a:layout_marginEnd="12dp"
           a:textAppearance="?android:attr/textAppearanceMedium" />
   </RelativeLayout>
```

>   I'm not sure if this is OK, or the ImageLoader should be able to issue that missing getArtist request to get all of the details of an Artist. Also, currently I've just reused the unknown album image for artists, maybe they should have a separate icon?

Maybe use `ic_contact_picture`? I think that looks better.

> * I've added some rounded corners to the icons, but they can be fully circular if that's better

If you think that is better rounded that circular, rounded! I only think in circular to difference the Artist list (rounded) and the Album list (square).

> * I think a "search/filter" box also can be added to this list, but maybe that is really deserves its own separate issue.

This is a great idea, but as you say it must have its own separate issue.

UPDATE:
I found a bug!, if you have an Artist that starts with a letter in lowercase (for example, __fun__) it appears at bottom of list instead of in F

To fix this maybe the better is pick the first letter of index name and do an `upper`?

**Comment by nitehu** [comment]
Thank you for these suggestions, I'll work on this for a few more days to finalize it the best I can :)

**Comment by nitehu** [comment]
I had very little time this week but everything seems to be fixed now:
- Added a fastscroll library. Unfortunately Zhanghai's require minimum sdk version 21, but I've found a similar and relatively maintained one which supports version 14.
- Added a real collation so the alphabetic ordering should work now
- Changed the unknown image
- Reduced margins in the artist row display
- Artist images can be turned on in the settings when id3 tags are used

Tested with Samsung Note9 with Android 10, Google Nexus S with Android 4.4.4 and various emulators.

**Comment by ogarcia** [comment]
Found a bug. If you have artists names that start with a number (like _3 Doors Down_) and you make scroll with the fast scroll, when you go to top it gives following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.moire.ultrasonic.debug, PID: 12362
    java.lang.ArrayIndexOutOfBoundsException: length=323; index=-1
        at java.util.Arrays$ArrayList.get(Arrays.java:3769)
        at org.moire.ultrasonic.activity.ArtistRowAdapter.getSectionName(ArtistRowAdapter.kt:147)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.scrollToPositionAtProgress(FastScrollRecyclerView.java:312)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScroller.handleTouchEvent(FastScroller.java:240)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.handleTouchEvent(FastScrollRecyclerView.java:156)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.onTouchEvent(FastScrollRecyclerView.java:136)
        at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3124)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3283)
        at android.view.View.dispatchTouchEvent(View.java:13482)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3804)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3476)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:756)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1881)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3501)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:708)
        at android.view.View.dispatchPointerEvent(View.java:13730)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6246)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6024)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5526)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5492)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5651)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5500)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5708)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5526)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5492)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5500)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8614)
E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8479)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8432)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8729)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8688)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8756)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:694)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/SubsonicTabActivity$SubsonicUncaughtExceptionHandler: Uncaught Exception! Android API level: 28
    Ultrasonic version name: 2.16.0
    Ultrasonic version code: 83
    java.lang.ArrayIndexOutOfBoundsException: length=323; index=-1
        at java.util.Arrays$ArrayList.get(Arrays.java:3769)
        at org.moire.ultrasonic.activity.ArtistRowAdapter.getSectionName(ArtistRowAdapter.kt:147)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.scrollToPositionAtProgress(FastScrollRecyclerView.java:312)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScroller.handleTouchEvent(FastScroller.java:240)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.handleTouchEvent(FastScrollRecyclerView.java:156)
        at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.onTouchEvent(FastScrollRecyclerView.java:136)
        at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3124)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3283)
        at android.view.View.dispatchTouchEvent(View.java:13482)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3804)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3476)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
E/SubsonicTabActivity$SubsonicUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3810)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:756)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1881)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3501)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:708)
        at android.view.View.dispatchPointerEvent(View.java:13730)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6246)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6024)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5526)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5492)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5651)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5500)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5708)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5526)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5492)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5500)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5473)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8614)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8479)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8432)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8729)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
E/SubsonicTabActivity$SubsonicUncaughtExceptionHandler:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8688)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8756)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:694)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Maybe the _#_ symbol not is in the list?

In the other hand. I think that is perfect :rocket:

**Comment by nitehu** [comment]
Thank you for finding this, and sorry it was just me not thinking straight... tried to retrieve the artist's name for the "Select folder" row 😓
Now it's fixed.
...
Oh no, wait, there is another bug if you scroll at the very end of the list... I'm on it...

**Comment by nitehu** [comment]
Ok so now it's fixed. I hope.

**Review by ogarcia — APPROVED** [review]
It works fine and is a great job :clap: :clap: :clap: 

I'll do merge and a new release

**Pull request merged**
