### PR TITLE
Target sdk 31 into develop

### PR DESCRIPTION
**Pull request by hmueller01**
see Target SDK 31 #731
see #752

### CODE REVIEW

**Comment by ogarcia** [comment]
@hmueller01 In order to merge this you will have to make a new branch and put the changes into a single signed commit. Otherwise it will not pass the checks and will not allow us to merge it.

**Comment by tzugen** [comment]
I have just done it.

**Review by tzugen — APPROVED** [review]
LGTM

**Comment by tzugen** [comment]
@hmueller01 Something is wrong with your git signing....

**Comment by hmueller01** [comment]
Thanks @tzugen for signing for me. I was sure I set the signoff config in this project. 

`git config format.signoff true`

But somehow it was gone. Hope next time it works ...

We now have 3 errors in AndroidStudio
```
Exported service does not require permission :68
Exported receiver does not require permission :78
Exported content providers can provide access to potentially sensitive data :154
```

> Exported content providers can provide access to potentially sensitive data 
> Inspection info:Content providers are exported by default and any application on the system can potentially use them to read and write data. If the content provider provides access to sensitive data, it should be protected by specifying export=false in the manifest or by protecting it with a permission that can be granted to other applications.


Should we add 

`tools:ignore="ExportedContentProvider"` ...

to these exports and take the risk?

**Comment by tzugen** [comment]
We can just leave it for now. The situation is unchanged to before just with 31 this warning has been introduced..

**Pull request merged**
