### PR TITLE
Use DiffUtil for better performance when refreshing the data..

### PR DESCRIPTION
**Pull request by tzugen**
See https://bignerdranch.com/blog/efficient-lists-with-diffutil-and-listadapter/ for more info on this

### CODE REVIEW

**Comment by tzugen** [comment]
This is the nice thing with these bases classes. When I improve the GenericRowAdapter all the changes are automatically in Artist and album List etc.

**Comment by tzugen** [comment]
I will add another commit today

**Comment by tzugen** [comment]
Now when you select an Album and then naviagte back, you end up at the scroll position where you left of, and not on the top.
This was annoying for long lists!

**Review by nitehu — APPROVED** [review]
Everything seems to be OK.

**Pull request merged**
