### PR TITLE
Mediastore to Kotlin, fix #383

### LINKED ISSUE #383: DownloadTask fails with "Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765"
## Problem description

If I try to download&pin an entire album by selecting all titles in the album and pressing the "pin" button, it starts downloading the first track 
and when it has finished it starts over in an endless loop.

Doing it in 2 steps (first downloading, then pinning) works fine.

It seems the error is because it tries to access external storage, which does not exist.

```
15:42:54.026: I SettingsFragment Enabled debug logging to file 
15:43:03.708: D RESTMusicService Loading cover art for: Entry(id=16745, parent=379, isDirectory=true, title=[em] Live, album=[em] Live, albumId=, artist=[em], artistId=, track=-1, year=2010, genre=Jazz, contentType=, suffix=, transcodedContentType=, transcodedSuffix=, coverArt=16745, size=-1, songCount=null, duration=-1, bitRate=-1, path=, isVideo=false, starred=false, discNumber=-1, type=, created=Tue Jan 30 18:44:22 GMT+01:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:03.881: I FileUtil getSampledBitmap 275 
15:43:04.636: D RESTMusicService Loading cover art for: Entry(id=16754, parent=16745, isDirectory=false, title=Break It, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=10, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27334981, songCount=null, duration=254, bitRate=848, path=[em]/[em] Live/10 Break It.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:41 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:04.792: I FileUtil getSampledBitmap 512 
15:43:08.005: I DownloadQueueSerializer Serialized currentPlayingIndex: 13, currentPlayingPosition: 111968 
15:43:08.005: I CancellableTask Starting thread for DownloadTask (Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
15:43:08.008: I DownloadFile$DownloadTask Acquired wake lock WakeLock{8aa69f7 held=true, refCount=1} 
15:43:08.012: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
15:43:11.151: I DownloadFile$DownloadTask Downloaded 2,11 MB of Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:14.150: I DownloadFile$DownloadTask Downloaded 4,41 MB of Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:16.359: I DownloadFile$DownloadTask Downloaded 6360000 bytes to /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.partial.mp3 
15:43:16.371: D RESTMusicService Loading cover art for: Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null) 
15:43:16.604: I FileUtil getSampledBitmap 1080 
15:43:16.655: I Util Renamed /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.partial.mp3 to /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.mp3 
15:43:16.813: I Util Deleted file /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/[em]/[em] Live/01-Blüten.mp3 
15:43:16.814: W DownloadFile$DownloadTask Failed to download 'Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)'.
java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1183)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at org.moire.ultrasonic.service.MediaStoreService.insertAlbumArt(SourceFile:107)
	at org.moire.ultrasonic.service.MediaStoreService.saveInMediaStore(SourceFile:77)
	at org.moire.ultrasonic.service.DownloadFile$DownloadTask.execute(SourceFile:401)
	at org.moire.ultrasonic.util.CancellableTask$1.run(SourceFile:84)
 java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/albumart/-1128604765
15:43:16.817: I DownloadFile$DownloadTask Released wake lock WakeLock{8aa69f7 held=false, refCount=0} 
15:43:16.827: I CancellableTask Stopping thread for DownloadTask (Entry(id=16755, parent=16745, isDirectory=false, title=Blüten, album=[em] Live, albumId=1199, artist=[em], artistId=374, track=1, year=2010, genre=Jazz, contentType=audio/flac, suffix=flac, transcodedContentType=audio/mpeg, transcodedSuffix=mp3, coverArt=16745, size=27860171, songCount=null, duration=263, bitRate=836, path=[em]/[em] Live/01 Blüten.flac, isVideo=false, starred=false, discNumber=1, type=music, created=Sun Aug 19 23:21:33 GMT+02:00 2018, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null)) 
```

### Steps to reproduce

1. select album that is not cached
2. pin album

## System information

 * **Ultrasonic version**: 2.18.0
 * **Android version**: 11
 * **Device info**: Google Pixel 4a

### PR DESCRIPTION
**Pull request by tzugen**
The URI of the album_art database was hardcoded, thus failing on some platforms.
It is now correctly generated.

Also remove scanMedia(), as ACTION_MEDIA_SCANNER_SCAN_FILE is deprecated,
in favour of the MediaStore API which we are already using (and is available since API 1)

### CODE REVIEW

**Review by nitehu — APPROVED** [review]
Review OK
Could you please change the copyright the same way as in #413 ?

**Comment by tzugen** [comment]
Ok, license is updated. Preferably merge this PR first, I will have to rebase the other one afterwards :)

**Comment by nitehu** [comment]
Tested it on a few phones and it seems to be working fine.

**Comment by tzugen** [comment]
@SaintDubious Was this exception caught or uncaught?

**Comment by tzugen** [comment]
I opened a bug about this: #435
If there was an uncaught exeception, we should tag it with 2.20.X, otherwise it can be done later, as
this PR didn't introduce the problem.

**Comment by SaintDubious** [comment]
Sorry, should have mentioned that the exception was caught.

**Pull request merged**
