### PR TITLE
Polish language support

### PR DESCRIPTION
**Pull request by bator-mikolaj**
Polish language support, verified and tested.

### CODE REVIEW

**Comment by ogarcia** [comment]
Sorry @bator-mikolaj but to send a new translation you must use [Transifex team](https://www.transifex.com/ultrasonic/ultrasonic/)

**Comment by Tapchicoma** [comment]
@ogarcia I think Polish is already translated on Transifex side: https://www.transifex.com/ultrasonic/ultrasonic/language/pl_PL/

So it is safe to merge this PR.

**Review by Tapchicoma — APPROVED** [review]
Looks good from my side!

**Comment by mbsrz1972** [comment]
I made this Transifex translation and @bator-mikolaj took it and made app for me, cause I'm not familiar to coding and github etc.

**Comment by ogarcia** [comment]
@Tapchicoma Ok, we could merge it without problems, but not in master (all PR must be in develop). Anyway if we merge this translation, it will be overwritten with Transifex one in next release.
@mbsrz1972 and @bator-mikolaj if this translation is the same that the Transifex one it will be included in next release.

**Comment by mbsrz1972** [comment]
@ogarcia Yes, it is the same translation

**Comment by ogarcia** [comment]
@mbsrz1972 Ok, then I close this PR because the translation will be picked from Transifex in next release :wink:

**Comment by Tapchicoma** [comment]
@ogarcia still for app to contain PL language this line should be added:
```
resConfigs "en", "es", "fr", "pl", "hu", "pt", "pt-rBR"
```

**Comment by Tapchicoma** [comment]
maybe just update it with all languages in transifex project

**Pull request closed without merging**
