### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by palto42**
Added translation for German language.

### CODE REVIEW

**Comment by palto42** [comment]
If #263 is merged, I will provide the translation for the new 5-star feature.

**Comment by palto42** [comment]
Just saw in other closed PR that translations are only accepted via Transifex team, so closing it here.
I requested German in Transifex and will provide my translation there as soon as it's added.

**Comment by palto42** [comment]
I added the German translation to Transifex, what do I need to do to get it added into the project now?
As far as I can see the "About" html file is not translated via Transifex, so I keep the PR (which includes it) open for now.

**Comment by ogarcia** [comment]
Hi,

For about, send a PR with only about file translated. The Transifex translations are added _automagically_ in every update ;-)

**Comment by palto42** [comment]
Hi @ogarcia ,
Thanks for your clarification, I just created a separate PR #265 for the About file and close this one.

**Pull request closed without merging**
