### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by tzugen**
For more info see the discussion :
https://github.com/ultrasonic/ultrasonic/discussions/449

### CODE REVIEW

**Comment by tzugen** [comment]
target_branch: develop is missing! 

And should we do it maybe rather weekly for starters?

**Comment by ogarcia** [comment]
@tzugen I think that is better weekly

**Comment by tzugen** [comment]
Ok, I set it to weekly and configured the target_branch.
I think we can try it out :)

**Comment by nitehu** [comment]
Wow, it already wants to update things...
What do you guys think should be the procedure here? For example the gradle update has failed.

**Pull request merged**
